<div style=" background-color: RGB(0,114,200);" >
<h1 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">PROJET 4 DATA ANALYST</h1>
<h2 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">Réalisez une étude de santé publique avec R ou Python
</h2>
</div>

# OBJECTIF DE CE NOTEBOOK

Bienvenue dans l'outil plébiscité par les analystes de données Jupyter.

Il s'agit d'un outil permettant de mixer et d'alterner codes, textes et graphique.

Cet outil est formidable pour plusieurs raisons:

+ il permet de tester des lignes de codes au fur et à mesure de votre rédaction, de constater immédiatement le résultat d'un instruction, de la corriger si nécessaire.
+ De rédiger du texte pour expliquer l'approche suivie ou les résultats d'une analyse et de le mettre en forme grâce à du code html ou plus simple avec **Markdown**
+ d'agrémenter de graphiques

Pour vous aider dans vos premiers pas à l'usage de Jupyter et de Python, nous avons rédigé ce notebook en vous indiquant les instructions à suivre.

Il vous suffit pour cela de saisir le code Python répondant à l'instruction donnée.

Vous verrez de temps à autre le code Python répondant à une instruction donnée mais cela est fait pour vous aider à comprendre la nature du travail qui vous est demandée.

Et garder à l'esprit, qu'il n'y a pas de solution unique pour résoudre un problème et qu'il y a autant de résolutions de problèmes que de développeurs ;)...

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.1 - Importation des librairies</h3>
</div>

In [1]:
#Importation de la librairie Pandas
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.2 - Chargement des fichiers Excel</h3>
</div>

In [ ]:
#Importation du fichier population.csv
population = pd.read_csv('population.csv')

#Importation du fichier dispo_alimentaire.csv
dispo_alimentaire = pd.read_csv('dispo_alimentaire.csv')

#Importation du fichier aide_alimentaire.csv
aide_alimentaire = pd.read_csv('aide_alimentaire.csv')

#Importation du fichier sous_nutrition.csv
sous_nutrition = pd.read_csv('sous_nutrition.csv')

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 - Analyse exploratoire des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.1 - Analyse exploratoire du fichier population</h3>
</div>

In [ ]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(population.shape[0]))
print("Le tableau comporte {} colonne(s)".format(population.shape[1]))

Le tableau comporte 1416 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [ ]:
#Consulter le nombre de colonnes
#La nature des données dans chacune des colonnes
#Le nombre de valeurs présentes dans chacune des colonnes
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1416 entries, 0 to 1415
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Zone    1416 non-null   object
 1   Année   1416 non-null   int64
 2   Valeur  1416 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 33.3+ KB

In [ ]:
#Affichage les 5 premières lignes de la table
population.head()

          Zone  Année     Valeur
0  Afghanistan   2013  32269.589
1  Afghanistan   2014  33370.794
2  Afghanistan   2015  34413.603
3  Afghanistan   2016  35383.032
4  Afghanistan   2017  36296.113

In [ ]:
#Nous allons harmoniser les unités. Pour cela, nous avons décidé de multiplier la population par 1000
#Multiplication de la colonne valeur par 1000

population['Valeur']*=1000

In [ ]:
#changement du nom de la colonne Valeur par Population
population.rename(columns={"Valeur":"Population"},inplace=True)

In [ ]:
#Affichage les 5 premières lignes de la table pour voir les modifications
population.head()

          Zone  Année  Population
0  Afghanistan   2013  32269589.0
1  Afghanistan   2014  33370794.0
2  Afghanistan   2015  34413603.0
3  Afghanistan   2016  35383032.0
4  Afghanistan   2017  36296113.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.2 - Analyse exploratoire du fichier disponibilité alimentaire</h3>
</div>

In [ ]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(dispo_alimentaire.shape[0]))
print("Le tableau comporte {} colonne(s)".format(dispo_alimentaire.shape[1]))

Le tableau comporte 15605 observation(s) ou article(s)
Le tableau comporte 18 colonne(s)

In [ ]:
#Consulter le nombre de colonnes
dispo_alimentaire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15605 entries, 0 to 15604
Data columns (total 18 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Zone                                                           15605 non-null  object
 1   Produit                                                        15605 non-null  object
 2   Origine                                                        15605 non-null  object
 3   Aliments pour animaux                                          2720 non-null   float64
 4   Autres Utilisations                                            5496 non-null   float64
 5   Disponibilité alimentaire (Kcal/personne/jour)                 14241 non-null  float64
 6   Disponibilité alimentaire en quantité (kg/personne/an)         14015 non-null  float64
 7   Disponibilité de matière grasse en quantité (g/personne/jour)  11794 non-null  float64
 8   Disponibilité de protéines en quantité (g/personne/jour)       11561 non-null  float64
 9   Disponibilité intérieure                                       15382 non-null  float64
 10  Exportations - Quantité                                        12226 non-null  float64
 11  Importations - Quantité                                        14852 non-null  float64
 12  Nourriture                                                     14015 non-null  float64
 13  Pertes                                                         4278 non-null   float64
 14  Production                                                     9180 non-null   float64
 15  Semences                                                       2091 non-null   float64
 16  Traitement                                                     2292 non-null   float64
 17  Variation de stock                                             6776 non-null   float64
dtypes: float64(15), object(3)
memory usage: 2.1+ MB

In [ ]:
#Affichage les 5 premières lignes de la table
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
#remplacement des NaN dans le dataset par des 0
dispo_alimentaire=dispo_alimentaire.fillna(0)

In [ ]:
#multiplication de toutes les lignes contenant des milliers de tonnes en Kg
dispo_alimentaire['Aliments pour animaux']=dispo_alimentaire['Aliments pour animaux']*1E6
dispo_alimentaire['Autres Utilisations']=dispo_alimentaire['Autres Utilisations']*1E6
dispo_alimentaire['Disponibilité intérieure']=dispo_alimentaire['Disponibilité intérieure']*1E6
dispo_alimentaire['Exportations - Quantité']=dispo_alimentaire['Exportations - Quantité']*1E6
dispo_alimentaire['Importations - Quantité']=dispo_alimentaire['Importations - Quantité']*1E6
dispo_alimentaire['Nourriture']=dispo_alimentaire['Nourriture']*1E6
dispo_alimentaire['Pertes']=dispo_alimentaire['Pertes']*1E6
dispo_alimentaire['Production']=dispo_alimentaire['Production']*1E6
dispo_alimentaire['Semences']=dispo_alimentaire['Semences']*1E6
dispo_alimentaire['Traitement']=dispo_alimentaire['Traitement']*1E6
dispo_alimentaire['Variation de stock']=dispo_alimentaire['Variation de stock']*1E6

In [ ]:
#Affichage les 5 premières lignes de la table
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier aide alimentaire</h3>
</div>

In [ ]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(aide_alimentaire.shape[0]))
print("Le tableau comporte {} colonne(s)".format(aide_alimentaire.shape[1]))

Le tableau comporte 1475 observation(s) ou article(s)
Le tableau comporte 4 colonne(s)

In [ ]:
#Consulter le nombre de colonnes
aide_alimentaire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pays bénéficiaire  1475 non-null   object
 1   Année              1475 non-null   int64
 2   Produit            1475 non-null   object
 3   Valeur             1475 non-null   int64
dtypes: int64(2), object(2)
memory usage: 46.2+ KB

In [ ]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head(5)

  Pays bénéficiaire  Année              Produit  Valeur
0       Afghanistan   2013  Autres non-céréales     682
1       Afghanistan   2014  Autres non-céréales     335
2       Afghanistan   2013         Blé et Farin   39224
3       Afghanistan   2014         Blé et Farin   15160
4       Afghanistan   2013             Céréales   40504

In [ ]:
#changement du nom de la colonne Pays bénéficiaire par Zone
aide_alimentaire=aide_alimentaire.rename(columns={"Pays bénéficiaire":"Zone"});

In [ ]:
#Multiplication de la colonne Aide_alimentaire qui contient des tonnes par 1000 pour avoir des kg
aide_alimentaire['Valeur']=aide_alimentaire['Valeur']*1000;

In [ ]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head()

          Zone  Année              Produit    Valeur
0  Afghanistan   2013  Autres non-céréales    682000
1  Afghanistan   2014  Autres non-céréales    335000
2  Afghanistan   2013         Blé et Farin  39224000
3  Afghanistan   2014         Blé et Farin  15160000
4  Afghanistan   2013             Céréales  40504000

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier sous nutrition</h3>
</div>

In [ ]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(sous_nutrition.shape[0]))
print("Le tableau comporte {} colonne(s)".format(sous_nutrition.shape[1]))

Le tableau comporte 1218 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [ ]:
#Consulter le nombre de colonnes
sous_nutrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Zone    1218 non-null   object
 1   Année   1218 non-null   object
 2   Valeur  624 non-null    object
dtypes: object(3)
memory usage: 28.7+ KB

In [ ]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head(5)

          Zone      Année Valeur
0  Afghanistan  2012-2014    8.6
1  Afghanistan  2013-2015    8.8
2  Afghanistan  2014-2016    8.9
3  Afghanistan  2015-2017    9.7
4  Afghanistan  2016-2018   10.5

In [ ]:
#Conversion of the sous nutrition column to numeric
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'], errors='coerce')

In [ ]:
#Conversion de la colonne (avec l'argument errors=coerce qui permet de convertir automatiquement les lignes qui ne sont pas des nombres en NaN)
#Puis remplacement des NaN en 0
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'], errors='coerce')
sous_nutrition=sous_nutrition.fillna(0)

In [ ]:
#changement du nom de la colonne Valeur par sous_nutrition
sous_nutrition = sous_nutrition.rename(columns={'Valeur':'Sous_nutrition'});

In [ ]:
#Multiplication de la colonne sous_nutrition par 1000000
sous_nutrition['Sous_nutrition']=sous_nutrition['Sous_nutrition']*1E6

In [ ]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head()

          Zone      Année  Sous_nutrition
0  Afghanistan  2012-2014       8600000.0
1  Afghanistan  2013-2015       8800000.0
2  Afghanistan  2014-2016       8900000.0
3  Afghanistan  2015-2017       9700000.0
4  Afghanistan  2016-2018      10500000.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.1 - Proportion de personnes en sous nutrition</h3>
</div>

In [ ]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2017
# Extract the average year from the 'Année' column in sous_nutrition
sous_nutrition['Année'] = sous_nutrition['Année'].str.split('-').apply(lambda x: (int(x[0]) + int(x[1])) / 2 if isinstance(x, list) and len(x) == 2 else None)

# Convert the 'Année' column to integer type
sous_nutrition['Année'] = sous_nutrition['Année'].astype(int)

#jointure entre les tables population et sous_nutrition en ciblant l'année selon la zone et l'année
jointure_population_sous_nutrition=pd.merge(population,sous_nutrition,how='inner',on=['Année','Zone'])
jointure_population_sous_nutrition=jointure_population_sous_nutrition[jointure_population_sous_nutrition['Année']==2017]
jointure_population_sous_nutrition=jointure_population_sous_nutrition.fillna(0)

In [ ]:
#Affichage du dataset
jointure_population_sous_nutrition.head()

              Zone  Année  Population  Sous_nutrition
4      Afghanistan   2017  36296113.0      10500000.0
10  Afrique du Sud   2017  57009756.0       3100000.0
16         Albanie   2017   2884169.0        100000.0
22         Algérie   2017  41389189.0       1300000.0
28       Allemagne   2017  82658409.0             0.0

In [ ]:
#Calcul et affichage du nombre de personnes en état de sous nutrition
nombre_personnes_sous_nutrition=jointure_population_sous_nutrition['Sous_nutrition'].sum()
population_totale=jointure_population_sous_nutrition['Population'].sum()
proportion_personnes_sous_nutrition=(nombre_personnes_sous_nutrition/population_totale)*100
print("La proportion de personnes en situation de sous_nutrition est de {} %".format(round(proportion_personnes_sous_nutrition)))

La proportion de personnes en situation de sous_nutrition est de 7 %

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.2 - Nombre théorique de personne qui pourrait être nourries</h3>
</div>

In [ ]:
#Combien mange en moyenne un être humain ? Source => https://www.vidal.fr/sante/nutrition/equilibre-alimentaire-adulte/recommandations-nutritionnelles-adulte.html

#2000 en moyenne pour les femmes, 2500 en moyenne pour les hommes => 2250 kcal par jour en moyenne

In [ ]:
#On commence par faire une jointure entre le data frame population et Dispo_alimentaire afin d'ajouter dans ce dernier la population
jointure_population_dispo_alimentaire=pd.merge(population[population['Année']==2017],dispo_alimentaire,how='inner',on=['Zone'])

In [ ]:
#Affichage du nouveau dataframe
jointure_population_dispo_alimentaire.head()

,Zone,Année,Population,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,2017,36296113.0,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0
1,Afghanistan,2017,36296113.0,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,2017,36296113.0,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,2017,36296113.0,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,2017,36296113.0,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Création de la colonne dispo_kcal avec calcul des kcal disponibles mondialement
jointure_population_dispo_alimentaire['dispo_kcal']=jointure_population_dispo_alimentaire['Disponibilité alimentaire (Kcal/personne/jour)']*jointure_population_dispo_alimentaire['Population']

In [ ]:
#Calcul du nombre d'humains pouvant être nourris
jointure_population_dispo_alimentaire['Nombre_humains_nourris']=jointure_population_dispo_alimentaire['dispo_kcal']/2250
print("En 2017, nous aurions pu nourrir {} humains".format(round(jointure_population_dispo_alimentaire['Nombre_humains_nourris'].sum())))

En 2017, nous aurions pu nourrir 1625875740 humains

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.3 - Nombre théorique de personne qui pourrait être nourrie avec les produits végétaux</h3>
</div>

In [ ]:
#Transfert des données avec les végétaux dans un nouveau dataframe
donnees_vegetaux=jointure_population_dispo_alimentaire.query('Origine=="vegetale"').copy()
donnees_vegetaux.head()

,Zone,Année,Population,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,dispo_kcal,Nombre_humains_nourris
1,Afghanistan,2017,36296113.0,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,...,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,36296113.0,16131.605778
2,Afghanistan,2017,36296113.0,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,...,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,36296113.0,16131.605778
3,Afghanistan,2017,36296113.0,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,Afghanistan,2017,36296113.0,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,...,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0,145184452.0,64526.423111
6,Afghanistan,2017,36296113.0,Bière,vegetale,0.0,0.0,0.0,0.09,0.00,...,0.0,3000000.0,3000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [ ]:
#Calcul du nombre de kcal disponible pour les végétaux
donnees_vegetaux['dispo_kcal_vegetale']=donnees_vegetaux['Disponibilité alimentaire (Kcal/personne/jour)']*donnees_vegetaux['Population']

In [ ]:
#Calcul du nombre d'humains pouvant être nourris avec les végétaux
donnees_vegetaux['Nombre_humains_nourris']=donnees_vegetaux['dispo_kcal_vegetale']/2250
print("En 2017, nous aurions pu nourrir {} humains avec des végétaux".format(round(donnees_vegetaux['Nombre_humains_nourris'].sum())))

En 2017, nous aurions pu nourrir 7671450761 humains avec des végétaux

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.4 - Utilisation de la disponibilité intérieure</h3>
</div>

In [ ]:
#Calcul de la disponibilité totale
disponibilite_totale=jointure_population_dispo_alimentaire['Disponibilité intérieure'].sum()
print("La disponibilté totale d'aliments dans le monde est de {} kgs.".format(round(disponibilite_totale)))

La disponibilté totale d'aliments dans le monde est de 9733927000000 kgs.

In [ ]:
#création d'une boucle for pour afficher les différentes valeurs en fonction des colonnes aliments pour animaux, pertes, nourritures,
for element in ['Aliments pour animaux','Pertes','Nourriture','Autres Utilisations','Semences','Traitement'] :
  print(element, ":", round(jointure_population_dispo_alimentaire[element].sum()), "kgs, soit", round((jointure_population_dispo_alimentaire[element].sum()/disponibilite_totale)*100), "% de la disponibilité totale d'aliments")

Aliments pour animaux : 1288002000000 kgs, soit 13 % de la disponibilité totale d'aliments
Pertes : 452283000000 kgs, soit 5 % de la disponibilité totale d'aliments
Nourriture : 4805525000000 kgs, soit 49 % de la disponibilité totale d'aliments
Autres Utilisations : 858771000000 kgs, soit 9 % de la disponibilité totale d'aliments
Semences : 153317000000 kgs, soit 2 % de la disponibilité totale d'aliments
Traitement : 2185641000000 kgs, soit 22 % de la disponibilité totale d'aliments

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.5 - Utilisation des céréales</h3>
</div>

In [ ]:
#Création d'une liste avec toutes les variables

#"Blé", "Riz (Eq Blanchi)", "Orge", "Maïs", "Seigle","Avoine", "Millet", "Sorgho", "Céréales, Autres"
liste_cereales = ["Blé", "Riz (Eq Blanchi)", "Orge", "Maïs", "Seigle","Avoine", "Millet", "Sorgho", "Céréales, Autres"]

In [ ]:
#Création d'un dataframe avec les informations uniquement pour ces céréales

dispo_cereales = jointure_population_dispo_alimentaire[jointure_population_dispo_alimentaire['Produit'].isin(liste_cereales)]
display(dispo_cereales)

,Zone,Année,Population,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,dispo_kcal,Nombre_humains_nourris
7,Afghanistan,2017,36296113.0,Blé,vegetale,0.0,0.0,1369.0,160.23,4.69,...,0.0,1.173000e+09,4.895000e+09,775000000.0,5.169000e+09,322000000.0,0.0,-350000000.0,4.968938e+10,2.208417e+07
12,Afghanistan,2017,36296113.0,"Céréales, Autres",vegetale,0.0,0.0,0.0,0.00,0.00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00
32,Afghanistan,2017,36296113.0,Maïs,vegetale,200000000.0,0.0,21.0,2.50,0.30,...,0.0,1.000000e+06,7.600000e+07,31000000.0,3.120000e+08,5000000.0,0.0,0.0,7.622184e+08,3.387637e+05
34,Afghanistan,2017,36296113.0,Millet,vegetale,0.0,0.0,3.0,0.40,0.02,...,0.0,0.000000e+00,1.200000e+07,1000000.0,1.300000e+07,0.0,0.0,0.0,1.088883e+08,4.839482e+04
40,Afghanistan,2017,36296113.0,Orge,vegetale,360000000.0,0.0,26.0,2.92,0.24,...,0.0,1.000000e+07,8.900000e+07,52000000.0,5.140000e+08,22000000.0,0.0,0.0,9.436989e+08,4.194218e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15374,Zimbabwe,2017,14236595.0,Millet,vegetale,0.0,0.0,23.0,2.93,0.20,...,0.0,0.000000e+00,4.100000e+07,3000000.0,5.500000e+07,3000000.0,7000000.0,0.0,3.274417e+08,1.455296e+05
15382,Zimbabwe,2017,14236595.0,Orge,vegetale,3000000.0,0.0,2.0,0.24,0.01,...,10000000.0,1.600000e+07,3.000000e+06,4000000.0,6.000000e+07,1000000.0,55000000.0,0.0,2.847319e+07,1.265475e+04
15399,Zimbabwe,2017,14236595.0,Riz (Eq Blanchi),vegetale,0.0,0.0,101.0,10.09,0.19,...,1000000.0,1.560000e+08,1.430000e+08,0.0,0.000000e+00,0.0,15000000.0,2000000.0,1.437896e+09,6.390649e+05
15400,Zimbabwe,2017,14236595.0,Seigle,vegetale,0.0,0.0,0.0,0.00,0.00,...,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00
15402,Zimbabwe,2017,14236595.0,Sorgho,vegetale,1000000.0,0.0,33.0,4.06,0.30,...,0.0,6.000000e+06,5.700000e+07,5000000.0,6.900000e+07,5000000.0,25000000.0,18000000.0,4.698076e+08,2.088034e+05

In [ ]:
#Affichage de la proportion d'alimentation animale

print("Les céréales sont utilisés à {} % dans l'alimentation animale".format(round((dispo_cereales['Aliments pour animaux'].sum()/dispo_cereales['Disponibilité intérieure'].sum())*100)))

Les céréales sont utilisés à 36 % dans l'alimentation animale

In [ ]:
#Affichage de la proportion d'alimentation humaine
print("Les céréales sont utilisés à {} % dans l'alimentation humaine".format(round((dispo_cereales['Nourriture'].sum()/dispo_cereales['Disponibilité intérieure'].sum())*100)))

Les céréales sont utilisés à 43 % dans l'alimentation humaine

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.6 - Pays avec la proportion de personnes sous-alimentée la plus forte en 2017</h3>
</div>

In [ ]:
#Création de la colonne proportion par pays

jointure_population_sous_nutrition['Pourcentage_sous_nutrition'] = round((jointure_population_sous_nutrition['Sous_nutrition'] / jointure_population_sous_nutrition['Population'])*100)

In [ ]:
#affichage après trie des 10 pires pays

jointure_population_sous_nutrition.sort_values(by='Pourcentage_sous_nutrition',ascending=False).head(10)

,Zone,Année,Population,Sous_nutrition,Pourcentage_sous_nutrition
472,Haïti,2017,10982366.0,5300000.0,48.0
946,République populaire démocratique de Corée,2017,25429825.0,12000000.0,47.0
652,Madagascar,2017,25570512.0,10500000.0,41.0
604,Lesotho,2017,2091534.0,800000.0,38.0
1102,Tchad,2017,15016753.0,5700000.0,38.0
622,Libéria,2017,4702226.0,1800000.0,38.0
970,Rwanda,2017,11980961.0,4200000.0,35.0
730,Mozambique,2017,28649018.0,9400000.0,33.0
1120,Timor-Leste,2017,1243258.0,400000.0,32.0
4,Afghanistan,2017,36296113.0,10500000.0,29.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.7 - Pays qui ont le plus bénéficié d'aide alimentaire depuis 2013</h3>
</div>

In [ ]:
#calcul du total de l'aide alimentaire par pays

aide_alimentaire_pays=aide_alimentaire.groupby('Zone')['Valeur'].sum()

In [ ]:
#affichage après trie des 10 pays qui ont bénéficié le plus de l'aide alimentaire

aide_alimentaire_pays.sort_values(ascending=False).head(10)

Zone
République arabe syrienne           1858943000
Éthiopie                            1381294000
Yémen                               1206484000
Soudan du Sud                        695248000
Soudan                               669784000
Kenya                                552836000
Bangladesh                           348188000
Somalie                              292678000
République démocratique du Congo     288502000
Niger                                276344000
Name: Valeur, dtype: int64

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.8 - Evolution des 5 pays qui ont le plus bénéficiés de l'aide alimentaire entre 2013 et 2016</h3>
</div>

In [ ]:
#Création d'un dataframe avec la zone, l'année et l'aide alimentaire puis groupby sur zone et année

aide_alimentaire_evolution=aide_alimentaire.groupby(['Zone','Année'])['Valeur'].sum().reset_index()

display(aide_alimentaire_evolution)

            Zone  Année     Valeur
0    Afghanistan   2013  128238000
1    Afghanistan   2014   57214000
2        Algérie   2013   35234000
3        Algérie   2014   18980000
4        Algérie   2015   17424000
..           ...    ...        ...
223       Égypte   2013    1122000
224     Équateur   2013    1362000
225     Éthiopie   2013  591404000
226     Éthiopie   2014  586624000
227     Éthiopie   2015  203266000

[228 rows x 3 columns]

In [ ]:
#Création d'une liste contenant les 5 pays qui ont le plus bénéficiées de l'aide alimentaire

top_5_pays_aides = aide_alimentaire_pays.sort_values(ascending=False).head(5).index.tolist()
print("Les 5 pays qui ont bénéficié le plus de l'aide alimentaire sont :", top_5_pays_aides)

Les 5 pays qui ont bénéficié le plus de l'aide alimentaire sont : ['République arabe syrienne', 'Éthiopie', 'Yémen', 'Soudan du Sud', 'Soudan']

In [ ]:
#On filtre sur le dataframe avec notre liste

aide_alimentaire_evolution_top_5 =aide_alimentaire_evolution[aide_alimentaire_evolution.Zone.isin(top_5_pays_aides)]

In [ ]:
# Affichage des pays avec l'aide alimentaire par année
display(aide_alimentaire_evolution_top_5)

                          Zone  Année     Valeur
157  République arabe syrienne   2013  563566000
158  République arabe syrienne   2014  651870000
159  République arabe syrienne   2015  524949000
160  République arabe syrienne   2016  118558000
189                     Soudan   2013  330230000
190                     Soudan   2014  321904000
191                     Soudan   2015   17650000
192              Soudan du Sud   2013  196330000
193              Soudan du Sud   2014  450610000
194              Soudan du Sud   2015   48308000
214                      Yémen   2013  264764000
215                      Yémen   2014  103840000
216                      Yémen   2015  372306000
217                      Yémen   2016  465574000
225                   Éthiopie   2013  591404000
226                   Éthiopie   2014  586624000
227                   Éthiopie   2015  203266000

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.9 - Pays avec le moins de disponibilité par habitant</h3>
</div>

In [ ]:
#Calcul de la disponibilité en kcal par personne par jour par pays

jointure_population_dispo_alimentaire_par_pays=jointure_population_dispo_alimentaire.groupby('Zone')['Disponibilité alimentaire (Kcal/personne/jour)'].sum().reset_index()

In [ ]:
#Affichage des 10 pays qui ont le moins de dispo alimentaire par personne

jointure_population_dispo_alimentaire_par_pays.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)',ascending=True).head(10)

,Zone,Disponibilité alimentaire (Kcal/personne/jour)
127,République centrafricaine,1879.0
164,Zambie,1924.0
91,Madagascar,2056.0
0,Afghanistan,2087.0
65,Haïti,2089.0
132,République populaire démocratique de Corée,2093.0
150,Tchad,2109.0
165,Zimbabwe,2113.0
114,Ouganda,2126.0
152,Timor-Leste,2129.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.10 - Pays avec le plus de disponibilité par habitant</h3>
</div>

In [ ]:
#Affichage des 10 pays qui ont le plus de dispo alimentaire par personne

jointure_population_dispo_alimentaire_par_pays.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)',ascending=False).head(10)

                      Zone  Disponibilité alimentaire (Kcal/personne/jour)
11                Autriche                                          3770.0
16                Belgique                                          3737.0
157                Turquie                                          3708.0
169  États-Unis d'Amérique                                          3682.0
74                  Israël                                          3610.0
72                 Irlande                                          3602.0
75                  Italie                                          3578.0
89              Luxembourg                                          3540.0
166                 Égypte                                          3518.0
4                Allemagne                                          3503.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.11 - Exemple de la Thaïlande pour le Manioc</h3>
</div>

In [ ]:
#création d'un dataframe avec uniquement la Thaïlande

#filtrage des donnees
donnees_thailande_sous_nutrition=jointure_population_sous_nutrition[jointure_population_sous_nutrition['Zone']=='Thaïlande']
donnees_thailande_dispo_alimentaire=jointure_population_dispo_alimentaire[jointure_population_dispo_alimentaire['Zone']=='Thaïlande']

#jointure
donnees_thailande=pd.merge(donnees_thailande_sous_nutrition,donnees_thailande_dispo_alimentaire,how='inner',on=['Zone','Année'])

#suppression du doublon de colonne population
donnees_thailande=donnees_thailande.drop('Population_y',axis=1)
donnees_thailande=donnees_thailande.rename(columns={'Population_x':'Population'})

#affichage
donnees_thailande.head()

,Zone,Année,Population,Sous_nutrition,Pourcentage_sous_nutrition,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),...,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,dispo_kcal,Nombre_humains_nourris
0,Thaïlande,2017,69209810.0,6200000.0,9.0,Abats Comestible,animale,0.0,0.0,3.0,...,5.000000e+06,33000000.0,75000000.0,0.0,4.500000e+07,0.0,0.0,0.0,207629430.0,92279.746667
1,Thaïlande,2017,69209810.0,6200000.0,9.0,"Agrumes, Autres",vegetale,0.0,0.0,0.0,...,6.000000e+06,2000000.0,6000000.0,0.0,1.200000e+07,0.0,2000000.0,0.0,0.0,0.000000
2,Thaïlande,2017,69209810.0,6200000.0,9.0,"Alcool, non Comestible",vegetale,0.0,358000000.0,0.0,...,1.100000e+08,21000000.0,0.0,0.0,4.470000e+08,0.0,0.0,0.0,0.0,0.000000
3,Thaïlande,2017,69209810.0,6200000.0,9.0,Aliments pour enfants,vegetale,0.0,0.0,2.0,...,7.000000e+06,19000000.0,12000000.0,0.0,0.000000e+00,0.0,0.0,0.0,138419620.0,61519.831111
4,Thaïlande,2017,69209810.0,6200000.0,9.0,Ananas,vegetale,0.0,0.0,10.0,...,1.449000e+09,9000000.0,671000000.0,110000000.0,2.209000e+09,0.0,0.0,13000000.0,692098100.0,307599.155556

In [ ]:
#Calcul de la sous nutrition en Thaïlande

sous_nutrition_thailande=donnees_thailande_sous_nutrition['Sous_nutrition'].sum()

print("La Thaïlande comporte {} habitants dans une situation de sous nutrition, soit {} % de sa population totale".format(round(sous_nutrition_thailande), round(sous_nutrition_thailande/donnees_thailande_sous_nutrition['Population'].sum()*100)))

#Calcul de la disponibilité pour la Thaïlande

dispo_par_habitant_thailande=donnees_thailande['Disponibilité alimentaire (Kcal/personne/jour)'].sum()
print("La Thaïlande a une disponibilité alimentaire de {} kcal par habitant".format(round(dispo_par_habitant_thailande)))

La Thaïlande comporte 6200000 habitants dans une situation de sous nutrition, soit 9 % de sa population totale
La Thaïlande a une disponibilité alimentaire de 2785 kcal par habitant

In [ ]:
#filtre sur le manioc
donnees_thailande_manioc=donnees_thailande[donnees_thailande['Produit']=='Manioc']
display(donnees_thailande_manioc)

,Zone,Année,Population,Sous_nutrition,Pourcentage_sous_nutrition,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),...,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,dispo_kcal,Nombre_humains_nourris
50,Thaïlande,2017,69209810.0,6200000.0,9.0,Manioc,vegetale,1.800000e+09,2.081000e+09,40.0,...,2.521400e+10,1.250000e+09,871000000.0,1.511000e+09,3.022800e+10,0.0,0.0,0.0,2.768392e+09,1.230397e+06

In [ ]:
#détails de la disponibilité intérieure pour le manioc

for element in ['Aliments pour animaux','Pertes','Nourriture','Autres Utilisations','Semences','Traitement'] :
  print(element, ":", round(donnees_thailande_manioc[element].sum()), "kgs, soit", round((donnees_thailande_manioc[element].sum()/donnees_thailande_manioc['Disponibilité intérieure'].sum())*100), "% de la disponibilité totale de manioc")

for element in ['Exportations - Quantité','Importations - Quantité','Production'] :
  print(element, ":", round(donnees_thailande_manioc[element].sum()), "kgs, soit", round((donnees_thailande_manioc[element].sum()/donnees_thailande_manioc['Production'].sum())*100), "% de la production de manioc")

for element in ['Nombre_humains_nourris'] :
  print(element, ":", round(donnees_thailande_manioc[element].sum()), "soit", round((donnees_thailande_manioc[element].sum()/donnees_thailande_manioc['Population'].sum())*100), "% de sa population")

Aliments pour animaux : 1800000000 kgs, soit 29 % de la disponibilité totale de manioc
Pertes : 1511000000 kgs, soit 24 % de la disponibilité totale de manioc
Nourriture : 871000000 kgs, soit 14 % de la disponibilité totale de manioc
Autres Utilisations : 2081000000 kgs, soit 33 % de la disponibilité totale de manioc
Semences : 0 kgs, soit 0 % de la disponibilité totale de manioc
Traitement : 0 kgs, soit 0 % de la disponibilité totale de manioc
Exportations - Quantité : 25214000000 kgs, soit 83 % de la production de manioc
Importations - Quantité : 1250000000 kgs, soit 4 % de la production de manioc
Production : 30228000000 kgs, soit 100 % de la production de manioc
Nombre_humains_nourris : 1230397 soit 2 % de sa population

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 6 - Analyse complémentaires</h2>
</div>

In [ ]:
#Répartition de l'utilisation des céréales

for element in ['Aliments pour animaux','Pertes','Nourriture','Autres Utilisations','Semences','Traitement'] :
  print(element, ":", round(dispo_cereales[element].sum()), "kgs, soit", round((dispo_cereales[element].sum()/dispo_cereales['Disponibilité intérieure'].sum())*100), "% de la disponibilité totale d'aliments")

Aliments pour animaux : 859615000000 kgs, soit 36 % de la disponibilité totale d'aliments
Pertes : 106706000000 kgs, soit 4 % de la disponibilité totale d'aliments
Nourriture : 1020464000000 kgs, soit 43 % de la disponibilité totale d'aliments
Autres Utilisations : 232672000000 kgs, soit 10 % de la disponibilité totale d'aliments
Semences : 67719000000 kgs, soit 3 % de la disponibilité totale d'aliments
Traitement : 91781000000 kgs, soit 4 % de la disponibilité totale d'aliments

In [ ]:
#Part des céréales dans les alimentations humaines et animales

dispo_cereales_analyse=dispo_cereales.groupby(by='Produit')[['Aliments pour animaux','Nourriture']].sum()

display(dispo_cereales_analyse)

                  Aliments pour animaux    Nourriture
Produit
Avoine                     1.586500e+10  3.459000e+09
Blé                        1.216860e+11  4.505810e+11
Céréales, Autres           1.878200e+10  5.308000e+09
Maïs                       5.447460e+11  1.250000e+11
Millet                     3.290000e+09  2.304000e+10
Orge                       8.879800e+10  6.744000e+09
Riz (Eq Blanchi)           3.358100e+10  3.768300e+11
Seigle                     8.073000e+09  5.349000e+09
Sorgho                     2.479400e+10  2.415300e+10

In [ ]:
#Calcul du nombre théorique d'humains que pourrait nourrir la part de produits animaux utilisés comme nourriture

donnees_animaux=jointure_population_dispo_alimentaire.query('Origine=="animale" & Nourriture>0 & `Disponibilité intérieure`>0').copy()
donnees_animaux['proportion_nourriture']=donnees_animaux['Nourriture']/donnees_animaux['Disponibilité intérieure']
donnees_animaux['dispo_kcal_effectives']=donnees_animaux['Disponibilité alimentaire (Kcal/personne/jour)']*donnees_animaux['proportion_nourriture']*donnees_animaux['Population']
donnees_animaux['Nombre_humains_nourris_effectif']=donnees_animaux['dispo_kcal_effectives']/2250
print(round(donnees_animaux['Nombre_humains_nourris_effectif'].sum()))

1495714507

In [ ]:
# Calcul du nombre d'humains qui pourraient être nourris par les aliments destinés destinée aux animaux

donnees_alimentation_animale=jointure_population_dispo_alimentaire.query('`Aliments pour animaux` > 0').copy()
donnees_alimentation_animale['dispo_kcal_perdues']=((donnees_alimentation_animale['Disponibilité alimentaire (Kcal/personne/jour)']*donnees_alimentation_animale['Aliments pour animaux'])/donnees_alimentation_animale['Disponibilité intérieure'])*donnees_alimentation_animale['Population']
donnees_alimentation_animale['Nombre_humains_nourris_perdu']=donnees_alimentation_animale['dispo_kcal_perdues']/2250
print(round(donnees_alimentation_animale['Nombre_humains_nourris_perdu'].sum()))

745791543

In [ ]:
# Calcul du nombres d'humains qui pourraient être nourris par la part des céréales utilisés dans l'alimentation animale

donnees_alimentation_animale_cereales=dispo_cereales.query('`Aliments pour animaux` > 0').copy()
donnees_alimentation_animale_cereales['dispo_kcal_perdues']=((donnees_alimentation_animale_cereales['Disponibilité alimentaire (Kcal/personne/jour)']*donnees_alimentation_animale_cereales['Aliments pour animaux'])/donnees_alimentation_animale_cereales['Disponibilité intérieure'])*donnees_alimentation_animale_cereales['Population']
donnees_alimentation_animale_cereales['Nombre_humains_nourris_perdu']=donnees_alimentation_animale_cereales['dispo_kcal_perdues']/2250
print(round(donnees_alimentation_animale_cereales['Nombre_humains_nourris_perdu'].sum()))

576014003

In [ ]:
# Calcul du nombres d'humains qui pourraient être nourris par les diverses pertes

donnees_pertes=jointure_population_dispo_alimentaire.query('Pertes > 0').copy()
donnees_pertes['dispo_kcal_perdues']=((donnees_pertes['Disponibilité alimentaire (Kcal/personne/jour)']*donnees_pertes['Pertes'])/donnees_pertes['Disponibilité intérieure'])*donnees_pertes['Population']
donnees_pertes['Nombre_humains_nourris_perdu']=donnees_pertes['dispo_kcal_perdues']/2250
print(round(donnees_pertes['Nombre_humains_nourris_perdu'].sum()))

370325564